# Generated by Django 4.0.6 on 2022-08-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devansh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proid', models.CharField(max_length=15)),
                ('proname', models.CharField(max_length=30)),
                ('prodate', models.DateField()),
                ('prorate', models.IntegerField(max_length=2)),
                ('proexp', models.CharField(max_length=50)),
                ('prosuggest', models.CharField(max_length=50)),
            ],
        ),
    ]
